services:
  db:
    image: mysql:latest
    container_name: omnirent-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${OMNI_DB_PASS}
      MYSQL_DATABASE: ${OMNI_DB}
    ports:
      - ${OMNI_DB_PORT}:${DOCKER_PORT}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: null