spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.schema-locations=classpath:sql/schema.sql
spring.sql.init.data-locations=classpath:sql/inserts-test.sql

tokenPass=123

app.mail.from=test@test.com

app.front-url=www.frontend.com

stripe.api-key=123
stripe.webhook-secret=321

spring.security.oauth2.client.registration.google.client-id=test
spring.security.oauth2.client.registration.google.client-secret=test

spring.security.oauth2.client.registration.github.client-id=test
spring.security.oauth2.client.registration.github.client-secret=test

spring.mail.host=localhost
spring.mail.port=25
spring.mail.username=test@test.com
spring.mail.password=test
spring.mail.transport.protocol=smtp

spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.datasource.url=jdbc:mysql://localhost:3306/test
spring.datasource.username=test
spring.datasource.password=test

app.mail.consumers.enabled=false
app.payment.consumers.enabled=false
spring.rabbitmq.listener.simple.auto-startup=false
spring.rabbitmq.listener.direct.auto-startup=false

# LOGGING
logging.level.br.com.omnirent=info
logging.level.root=warn
spring.main.log-startup-info=false
spring.jpa.open-in-view=false
logging.level.org.springframework.web.servlet.handler.HandlerMappingIntrospector=error

spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.orm.jdbc.bind=off
logging.level.org.hibernate.SQL=DEBUG