tokenPass = 123

# LOGGING
spring.output.ansi.enabled=ALWAYS
logging.pattern.console=%clr(%d{HH:mm:ss}){cyan} %clr(%-5level){level} %clr(%logger{36}){cyan} - %msg%n

logging.level.br.com.omnirent=info
logging.level.root=warn
spring.main.log-startup-info=false
spring.jpa.open-in-view=false
logging.level.org.springframework.web.servlet.handler.HandlerMappingIntrospector=error

spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.orm.jdbc.bind=off
logging.level.org.hibernate.SQL=DEBUG