spring.application.name=omnirent
server.servlet.context-path=/api

app.locale=${APP_LOCALE:pt-BR}
app.timezone=${APP_TIMEZONE:America/Sao_Paulo}


spring.jpa.open-in-view=false
spring.main.log-startup-info=false

logging.level.br.com.omnirent=info
logging.level.root=warn

spring.output.ansi.enabled=ALWAYS
logging.pattern.console=%clr(%d{HH:mm:ss}){cyan} %clr(%-5level){level} %clr(%logger{36}){cyan} - %msg%n