spring.application.name=omnirent

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:sql/schema.sql
spring.sql.init.data-locations=classpath:sql/inserts.sql

spring.jpa.hibernate.ddl-auto=validate
spring.datasource.url=jdbc:mysql://${OMNI_DB_HOST}:${OMNI_DB_PORT}/${OMNI_DB}
spring.datasource.username=${OMNI_DB_USER}
spring.datasource.password=${OMNI_DB_PASS}