spring.application.name=omnirent

server.servlet.context-path=/api

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:sql/schema.sql
spring.sql.init.data-locations=classpath:sql/inserts.sql

spring.jpa.hibernate.ddl-auto=validate
spring.datasource.url=jdbc:mysql://${OMNI_DB_HOST}:${OMNI_DB_PORT}/${OMNI_DB}
spring.datasource.username=${OMNI_DB_USER}
spring.datasource.password=${OMNI_DB_PASS}

tokenPass=${TOKEN_PASS}

# LOGGING
spring.output.ansi.enabled=ALWAYS
logging.pattern.console=%clr(%d{HH:mm:ss}){cyan} %clr(%-5level){level} %clr(%logger{36}){cyan} - %msg%n

logging.level.br.com.omnirent=info
logging.level.root=warn
spring.main.log-startup-info=false
spring.jpa.open-in-view=false
logging.level.org.springframework.web.servlet.handler.HandlerMappingIntrospector=error

spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.orm.jdbc.bind=off
logging.level.org.hibernate.SQL=DEBUG