spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.schema-locations=classpath:sql/schema.sql
spring.sql.init.data-locations=classpath:sql/inserts-test.sql

tokenPass=123

app.mail.from=test@test.com

app.front-url=www.frontend.com

app.admin.name=System Administrator
app.admin.username=admin
app.admin.email=admin@omnirent.test
app.admin.password=Admin@123

stripe.api-key=123
stripe.webhook-secret=321

r2.access-key=test-access-key
r2.secret-key=test-secret-key
r2.endpoint=http://localhost:9000
r2.bucket=omnirent-images-test

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB

app.max-file-size=5MB
app.max-upload-size=25MB

spring.security.oauth2.client.registration.google.client-id=test
spring.security.oauth2.client.registration.google.client-secret=test

spring.security.oauth2.client.registration.github.client-id=test
spring.security.oauth2.client.registration.github.client-secret=test

rate.limit.window=10m
rate.limit.penalties=30s,1m,5m,15m,30m

spring.mail.host=localhost
spring.mail.port=25
spring.mail.username=test@test.com
spring.mail.password=test
spring.mail.transport.protocol=smtp

spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.datasource.url=jdbc:mysql://localhost:3306/test
spring.datasource.username=test
spring.datasource.password=test

app.mail.consumers.enabled=false
app.payment.consumers.enabled=false
spring.rabbitmq.listener.simple.auto-startup=false
spring.rabbitmq.listener.direct.auto-startup=false

# LOGGING
logging.level.br.com.omnirent=info
logging.level.root=warn
spring.main.log-startup-info=false
spring.jpa.open-in-view=false
logging.level.org.springframework.web.servlet.handler.HandlerMappingIntrospector=error

spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.orm.jdbc.bind=off
logging.level.org.hibernate.SQL=DEBUG